default_context:
    project_name: "Your Project"
    remote_url: "None"
    project_slug: "your-project"
    full_name: "Your Name"
    license: "MIT"
    use_submodules: "No"
    header_only: "No"
    external_dependency: "None"
    github_acitons_ci: "Yes"
    gitlab_ci: "No"
    readthedocs: "Yes"
    doxygen: "Yes"
    cxx_minimum_standard: "20"
    python_bindings: "No"
    pypi_release: "No"
    codecovio: "Yes"
