default_context:
    project_name: "Your Project"
    remote_url: "None"
    project_slug: "your-project"
    full_name: "Your Name"
    license: "MIT"
    use_submodules: false
    header_only: false
    external_dependency: "None"
    github_actions_ci: true
    gitlab_ci: false
    readthedocs: true
    doxygen: true
    cxx_minimum_standard: "20"
    python_bindings: "None"
    pypi_release: false
    codecovio: true
