repos:
{%- if cookiecutter.python_bindings %}
  # Run Black - the uncompromising Python code formatter
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black-jupyter
{%- endif %}

  # Format C++ code with Clang-Format - automatically applying the changes
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v16.0.6
    hooks:
      - id: clang-format
        args:
        - --style=Mozilla
        exclude: ^ext/

  # Add some general purpose useful hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # Make sure that contained YAML files are well-formed
      - id: check-yaml
      # Trim trailing whitespace of all sorts
      - id: trailing-whitespace
      # Apply a file size limit of 500kB
      - id: check-added-large-files
{%- if cookiecutter.python_bindings %}
      # Simple parser validation of e.g. pyproject.toml
      - id: check-toml
{%- endif %}
      # Unify file endings
      - id: end-of-file-fixer

  # CMake Formatting/Linting Utility
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
      - id: cmake-format
      - id: cmake-lint
