version: 2

build:
  os: ubuntu-26.04
  tools:
    python: "3.14"
  apt_packages:
    - cmake
    - doxygen
  jobs:
    pre_build:
      - cmake --preset documentation
      - cmake --build --preset documentation
    build:
      html:
        - sphinx-build -T -j auto -b html -d $READTHEDOCS_OUTPUT/doctrees -D language=en doc $READTHEDOCS_OUTPUT/html

python:
{% if cookiecutter.python_bindings == "pybind11" or cookiecutter.python_bindings == "nanobind" %}
  install:
    - method: uv
      command: sync
      path: python/{{ cookiecutter.__python_module }}
      extras:
        - docs
{% else %}
  install:
    - requirements: doc/requirements-rtd.txt
{% endif %}
sphinx:
  configuration: doc/conf.py
