exclude: ^({{cookiecutter.project_slug}}/)

repos:
  # Add some general purpose useful hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      # Make sure that contained YAML files are well-formed
      - id: check-yaml
      # Trim trailing whitespace of all sorts
      - id: trailing-whitespace
      # Apply a file size limit of 500kB
      - id: check-added-large-files
      # Unify file endings
      - id: end-of-file-fixer

  # GitHub Actions Workflow linter
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.11
    hooks:
      - id: actionlint
